<html>
<head>
</head>
<link rel = "stylesheet" href = "Index.CSS">
 
<body class = noMargin>
<main class="main" class = noMargin>
       
   
<div class="nav">
    <h1 class="tittel"> The Booking House</h1>
    <a href="/" class = link>Booking</a>
    <a href="Cafémenu.html" class = link>Café Menu</a>
    <a href="/" class = link>Access</a>
    <a href="/" class = link>Topical page</a>
</div>
   
 
   
<div class="grid-container">
    <div class="BookingPage"><h1>Booking</h1> In the booking page you are able to book appointments for using TBH(The Booking Hosue). The Booking House can be rented out when arranging events like birthday parties to marriage parties.</div>
    <div class="CaféMenu"><h1>Café Menu</h1> The Booking House has a Café that offers the best dishes in Oslo for a reasonable price. As of 2022 we are not accepting cryptocurrencies as a form of payment, as a result of multiple attemps of fraud.</div>
    <div class="Access"><h1>Access</h1>Here you will find how we who founded The Booking House have gone about the process. In this page you will get a glimpse of how the process went and </div>  
    <div class="TopicalPage"><h1>Topical page</h1>For Data 1100 text </div>
  </div>
</main>
 
</body>
 
 
</html>
